In [1]:
import ising.metropolis as metropolis
from ising.visualize import display_experiment
from ising.lattice_objects import *
from ising.data_analysis import *

In [2]:
WIDTH = 50
HEIGHT = 50

UP_SCALE = 4

In [3]:
#lattices = metropolis.simulate(lattice=square_random_lattice(width=WIDTH, height=HEIGHT, states=[-1, 0, 1]), J=0.2, B=2, T=120, steps=1000)
X = squarelattice2d(WIDTH, HEIGHT)


In [4]:
X.simulate(0.2, 2, 120, 10000)
gif = X.lattices_to_images(UP_SCALE)
selectedSimulations = X.simulation[-100:]


In [ ]:
lattice = X.simulation[-1]
#expSpin:float = lattice.sum(dtype=float) / lattice.size
#width, height = lattice.shape
#x:int = np.random.randint(width)
#y:int = np.random.randint(height)
#spinProduct:np.ndarray[int,int] = lattice[x,y] * lattice
#expSpinProduct:float = spinProduct.sum(dtype=float) / spinProduct.size
#expSpin, expSpinProduct, expSpinProduct - expSpin**2

getCorrelationCoefficient((5,7), lattice), getCorrelationCoefficient_2((5,7),X.simulation), 

In [5]:
c = getCorrelationCoefficient_3(selectedSimulations)
c

array([ 1.00010000e+00,  2.75469388e-02,  1.68145833e-02,  2.07787234e-02,
        2.97826087e-03,  8.51555556e-03,  5.44590909e-02,  2.46744186e-02,
       -2.63404762e-02,  1.01292683e-02, -2.31275000e-02,  1.57948718e-03,
        1.61342105e-02, -2.98702703e-02,  7.76111111e-03,  4.79171429e-02,
        2.10588235e-02, -2.27272727e-04, -1.43718750e-02, -1.42612903e-02,
       -4.39033333e-02,  1.74344828e-02,  4.88285714e-02, -1.69000000e-02,
       -1.21500000e-02, -7.16760000e-02, -6.89583333e-02, -1.05130435e-02,
       -2.02409091e-02,  2.45809524e-02,  3.25000000e-02,  2.64578947e-02,
        1.13944444e-02, -1.45941176e-02, -1.25000000e-03,  2.20000000e-04,
       -2.84714286e-02, -1.80615385e-02, -9.69166667e-02, -1.49818182e-02,
        1.83200000e-02, -6.75555556e-03,  6.83750000e-03,  6.61571429e-02,
        7.35666667e-02,  3.37600000e-02,  3.91250000e-02, -1.13000000e-02,
        2.53500000e-02, -3.28500000e-01])

In [6]:

d = c - (sum([Y.sum(dtype=float)/len(Y) for Y in selectedSimulations])/len(selectedSimulations))**2
d


array([ 0.95656637, -0.01598669, -0.02671904, -0.0227549 , -0.04055537,
       -0.03501807,  0.01092546, -0.01885921, -0.0698741 , -0.03340436,
       -0.06666113, -0.04195414, -0.02739942, -0.0734039 , -0.03577252,
        0.00438352, -0.0224748 , -0.0437609 , -0.0579055 , -0.05779492,
       -0.08743696, -0.02609914,  0.00529494, -0.06043363, -0.05568363,
       -0.11520963, -0.11249196, -0.05404667, -0.06377454, -0.01895267,
       -0.01103363, -0.01707573, -0.03213918, -0.05812774, -0.04478363,
       -0.04331363, -0.07200506, -0.06159517, -0.14045029, -0.05851545,
       -0.02521363, -0.05028918, -0.03669613,  0.02262352,  0.03003304,
       -0.00977363, -0.00440863, -0.05483363, -0.01818363, -0.37203363])

In [7]:
c2,d2 = getCorrelationCoefficient_4((25,25), selectedSimulations)
c2,d2

(array([ 1.0001 ,  0.0191 ,  0.19175,  0.2753 , -0.27485, -0.08575,
         0.018  , -0.3347 , -0.0703 ,  0.00335, -0.02975, -0.0106 ,
         0.0031 , -0.1414 ,  0.19925, -0.08745, -0.18445, -0.36855,
         0.21085, -0.35855, -0.09605,  0.097  ,  0.4502 ,  0.29105,
        -0.0228 ]),
 array([ 0.9713755 ,  0.01923557,  0.18344786,  0.26437621, -0.26503283,
        -0.08034912,  0.01907103, -0.3203835 , -0.0687443 ,  0.00434816,
        -0.03019231, -0.00917987,  0.00558098, -0.13602792,  0.19221885,
        -0.08539777, -0.17724939, -0.35685853,  0.20317488, -0.34187962,
        -0.0936385 ,  0.09371236,  0.43658509,  0.28017875, -0.01925138]))

In [8]:
n:int = len(c)
np.fromfunction(function=(lambda r : (r+1)**(-0.25)),shape=(n,), dtype=float)


array([1.        , 0.84089642, 0.75983569, 0.70710678, 0.6687403 ,
       0.6389431 , 0.61478815, 0.59460356, 0.57735027, 0.56234133,
       0.54910049, 0.53728497, 0.52664039, 0.51697315, 0.50813275,
       0.5       , 0.49247906, 0.48549177, 0.47897363, 0.4728708 ,
       0.46713798, 0.46173663, 0.45663379, 0.451801  , 0.4472136 ,
       0.44285001, 0.43869134, 0.43472087, 0.43092382, 0.42728701,
       0.42379866, 0.42044821, 0.41722614, 0.41412388, 0.41113362,
       0.40824829, 0.40546145, 0.4027672 , 0.40016016, 0.39763536,
       0.39518826, 0.39281465, 0.39051065, 0.38827268, 0.3860974 ,
       0.38398171, 0.38192276, 0.37991784, 0.37796447, 0.37606031])

In [ ]:
from ipywidgets import interact


display_experiment(gif)

In [ ]:
from ising.visualize import save_gif

save_gif(gif, "5-states-example")

In [ ]:
from ising.visualize import split_gif

split_gif("simulation-results/3-states-example", num_key_frames=25)

In [ ]:
import cv2
import numpy as np

def save_video(images: [np.array], filename: str) -> None:
    """Save simulation as video (.avi format)."""

    video = cv2.VideoWriter(
        f"simulation-results/{filename}.avi", cv2.VideoWriter_fourcc(*"I420"), 24
    )
    for image in images:
        video.write(image)

    return video



